# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESTEELAUDER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'BulletinBoard'
  target 'ESTEELAUDERTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ESTEELAUDERUITests' do
    # Pods for testing
  end

end
